apps/tarefas/urls.py
from django.urls import path

app_name = 'tarefas'

from . import views

urlpatterns = [
    #categorias
    path('adicionar-categoria/', views.adicionar_categoria, name='adicionar_categoria'),
    path('listar-categorias/', views.listar_categorias, name='listar_categorias'),
    path('apagar-categoria/<int:pk>/', views.apagar_categoria, name='apagar_categoria'),
    path('editar-categoria/<int:pk>/', views.editar_categoria, name='editar_categoria'),
    #tarefas
    path('adicionar-tarefa/', views.adicionar_tarefa, name='adicionar_tarefa'),
    path('listar-tarefas/', views.listar_tarefas, name='listar_tarefas'),
    path('listar-tarefas-concluidas/', views.listar_concluidas, name='listar_concluidas'),
    path('apagar-tarefa/<int:pk>', views.apagar_tarefa, name='apagar_tarefa'),
    path('editar-tarefa/<int:pk>', views.editar_tarefa, name='editar_tarefa'),
    # path('', views.pagina_inicial, name='pagina_inicial'),
]

todo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tarefas/', include('tarefas.urls', namespace='tarefas')),
    path('', include('paginas.urls', namespace='pagina_inicial')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tarefas/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model) :
    nome = models.CharField('Nome',max_length=50)
    descricao = models.TextField('Descrição', blank=True, null=True)

    def __str__(self):
        return self.nome


class Tarefas(models.Model):
    PRIORIDADE_CHOICE = (
        (1, 'Alta'),
        (2, 'Média'),
        (3, 'Baixa'),
    )

    STATUS_CHOICE= (
        ('AF', 'A Fazer'),
        ('PD', 'Pendente'),
        ('CD', 'Concluída'),
    )

    titulo = models.CharField('Título', max_length=100)
    descricao = models.TextField('Descrição')
    categoria = models.ForeignKey(Categoria, verbose_name='Categoria', on_delete=models.CASCADE)
    prioridade = models.PositiveIntegerField('Prioridade', choices=PRIORIDADE_CHOICE)
    status = models.CharField('Status',max_length=2, choices=STATUS_CHOICE, default='AF')

    def __str__(self):
        return self.titulo

apps/tarefas/forms.py
from django import forms

from .models import Categoria, Tarefas

class CategoriaForm(forms.ModelForm) :
    class Meta:
        model = Categoria
        fields = '__all__'
        # fields = ['nome', 'descricao']
        # exclude = ['descricao]

class TarefaForm(forms.ModelForm) :
    class Meta:
        model = Tarefas
        fields = '__all__'

apps/tarefas/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import CategoriaForm, TarefaForm
from .models import Categoria, Tarefas

# Create your views here.
# CRUD de categorias
@login_required(login_url='/login/')
def adicionar_categoria(request):
    template_name = 'tarefas/adicionar_categoria.html'
    context = {}
    if request.method == 'POST':
        form = CategoriaForm(request.POST) #dicionário : POST= {}
        if form.is_valid() :
            form.save()
            messages.success(request, 'Categoria adiciona com Sucesso')
            return redirect('tarefas:listar_categorias') # --> /tarefas/adicionar-categoria
    else:
        form = CategoriaForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/login/')
def listar_categorias(request):
    template_name = 'tarefas/listar_categorias.html'
    categorias = Categoria.objects.all()
    context = {
        'categorias' : categorias,
    }
    return render(request, template_name, context)

@login_required(login_url='/login/')
def apagar_categoria(request, pk):
    try:
        # Categoria.objects.get(pk=pk).delete()
        categoria = get_object_or_404(Categoria, pk=pk)
        categoria.delete()
    except Categoria.DoesNotExist :
        return redirect('/')
    messages.warning(request,'Categoria apagada!')
    return redirect('tarefas:listar_categorias')

@login_required(login_url='/login/')
def editar_categoria(request, pk):
    template_name = 'tarefas/adicionar_categoria.html'
    categoria = get_object_or_404(Categoria, pk=pk)
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria modificada')
            return redirect('tarefas:listar_categorias')
    else:
        form = CategoriaForm(instance=categoria)
    context = {
        'form' : form
    }
    return render(request, template_name, context)

# CRUD de tarefas
@login_required(login_url='/login/')
def adicionar_tarefa(request):
    template_name = 'tarefas/adicionar_tarefa.html'
    context = {}
    if request.method == 'POST' :
        form = TarefaForm(request.POST)
        if form.is_valid() :
            form.save()
            messages.success(request, 'Tarefa adiciona com sucesso')
            return redirect('tarefas:listar_tarefas')
    else :
        form = TarefaForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/login/')
def listar_tarefas(request):
    template_name = 'tarefas/listar_tarefas.html'
    tarefas = Tarefas.objects.all().exclude(status='CD')
    context = {
        'tarefas' : tarefas,
    }
    return render(request, template_name, context)

@login_required(login_url='/login/')
def editar_tarefa(request, pk) :
    template_name = 'tarefas/adicionar_tarefa.html'
    tarefa = get_object_or_404(Tarefas, pk=pk)
    if tarefa.status != 'CD':
        if request.method == 'POST':
            form = TarefaForm(request.POST, instance=tarefa)
            if form.is_valid():
                form.save()
                messages.success(request, 'Tarefa modificada')
                return redirect('tarefas:listar_tarefas')
        else:
            form = TarefaForm(instance=tarefa)
        context = {
            'form' : form,
        }
    else:
       return redirect('tarefas:listar_tarefas')
    return render(request, template_name, context)

@login_required(login_url='/login/')
def apagar_tarefa(request, pk) :
    tarefa = get_object_or_404(Tarefas, pk=pk)
    if tarefa.status != 'CD':
        try:
            tarefa.delete()
        except Tarefas.DoesNotExist :
            return redirect('/')
        messages.warning(request, 'Tarefa apagada')
    return redirect('tarefas:listar_tarefas')

@login_required(login_url='/login/')
def listar_concluidas(request):
    template_name= 'tarefas/listar_concluidas.html'
    tarefas = Tarefas.objects.filter(status='CD')
    context = {
        'tarefas' : tarefas,
    }
    return render(request, template_name, context)

templates/tarefas/adicionar_categoria.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block titulo %}

    {{ block.super }} | Categoria

{% endblock titulo %}

{% block corpo %}

    <h1>Categoria</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nome.id_for_label }}">Nome</label>
            {% render_field form.nome class="form-control" placeholder="Digite o nome da categoria" %}
        </div>
        <div class="form-group">
            <label for="{{ form.descricao.id_for_label }}">Descrição</label>
            {% render_field form.descricao class="form-control" placeholder="Opcional. Digite a descrição da categoria" %}
        </div>
        <div class="mt-2">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a class="btn btn-secondary" href=" {% url 'tarefas:listar_categorias' %}">Cancelar</a>
        </div>
    </form>

{% endblock corpo %}

templates/tarefas/adicionar_tarefa.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block titulo %}

    {{ block.super}} | Adiconar Categoria

{% endblock titulo %}

{% block corpo %}

    <h1>Tarefas</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.titulo.id_for_label }}">Titulo</label>
            {% render_field form.titulo class="form-control" placeholder="Digite o título da tarefa" %}
        </div>
        <div class="form-group">
            <label for="{{ form.descricao.id_for_label }}">Descrição</label>
            {% render_field form.descricao class="form-control" placeholder="Digite a descrição da categoria" %}
        </div>
        <div class="d-flex justify-content-between">
            <div class="form-group w-25">
                <label for="{{ form.categoria.id_for_label}}">Categoria</label>
                {% render_field form.categoria class="form-control" placeholder="Escolha a Categoria da tarefa" %}
            </div>
            <div class="form-group w-25">
                <label for="{{ form.status.id_for_label}}">Status</label>
                {% render_field form.status class="form-control" placeholder="Escolha o Status da tarefa" %}
            </div>
            <div class="form-group w-25">
                <label for="{{ form.prioridade.id_for_label }}">Prioridade</label>
                {% render_field form.prioridade class="form-control" placeholder="Escolha a prioridade da tarefa" %}
            </div>
        </div>
        <div class="mt-2">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a class="btn btn-secondary" href=" {% url 'tarefas:listar_tarefas' %}">Cancelar</a>
        </div>

    </form>

{% endblock corpo %}

templates/tarefas/listar_categorias.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block titulo %}

    {{ block.super}} | Categoria

{% endblock titulo %}

{% block corpo %}

    <h1>Categorias</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
                <tr>
                    <th scope="row">{{ categoria.id }}</th>
                    <td>{{ categoria.nome }}</td>
                    <td>{{ categoria.descricao }}</td>
                    <td>
                        <a class="btn btn-info btn-sm" href="{% url 'tarefas:editar_categoria' categoria.id %}">Editar</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'tarefas:apagar_categoria' categoria.id %}">Apagar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

<a class="btn btn-primary" href="{% url 'tarefas:adicionar_categoria' %}"  >
   Adicionar Nova Categoria
</a>

{% endblock corpo %}

templates/tarefas/listar_concluidas.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block titulo %}

    {{ block.super }} | Tarefa

{% endblock titulo %}

{% block corpo %}

    <h1>Tarefas</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Descrição</th>
                <th scope="col">Categoria</th>
                <th scope="col">Status</th>
                <th scope="col">Prioridade</th>
            </tr>
        </thead>
        <tbody>
            {% for tarefa in tarefas %}
                <tr>
                    <th scope="row">{{ tarefa.id }}</th>
                    <td>{{ tarefa.titulo }}</td>
                    <td>{{ tarefa.descricao }}</td>
                    <td>{{ tarefa.categoria }}</td>
                    <td>{{ tarefa.get_status_display }}</td>
                    <td>{{ tarefa.get_prioridade_display }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock corpo %}

templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block titulo %}

    {{ block.super }} | Tarefa

{% endblock titulo %}

{% block corpo %}

    <h1>Tarefas</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Descrição</th>
                <th scope="col">Categoria</th>
                <th scope="col">Status</th>
                <th scope="col">Prioridade</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for tarefa in tarefas %}
                <tr>
                    <th scope="row">{{ tarefa.id }}</th>
                    <td>{{ tarefa.titulo }}</td>
                    <td>{{ tarefa.descricao }}</td>
                    <td>{{ tarefa.categoria }}</td>
                    <td>{{ tarefa.get_status_display }}</td>
                    <td>{{ tarefa.get_prioridade_display }}</td>
                    <td>
                        <a class="btn btn-info btn-sm" href="{% url 'tarefas:editar_tarefa' tarefa.id %}">Editar</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'tarefas:apagar_tarefa' tarefa.id %}">Apagar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'tarefas:adicionar_tarefa' %}" class="btn btn-primary">Adicionar Nova Tarefa</a>

{% endblock corpo %}