apps/paginas/urls.py
from django.urls import path

app_name = 'paginas'

from . import views

urlpatterns = [
    path('login/', views.fazer_login, name='fazer_login'),
    path('logout/', views.fazer_logout, name='fazer_logout'),
    path('', views.pagina_inicial, name='pagina_inicial'),
]

apps/tarefas/urls.py
from django.urls import path

app_name = 'tarefas'

from . import views

urlpatterns = [
    #categorias
    path('adicionar-categoria/', views.adicionar_categoria, name='adicionar_categoria'),
    path('listar-categorias/', views.listar_categorias, name='listar_categorias'),
    path('apagar-categoria/<int:pk>/', views.apagar_categoria, name='apagar_categoria'),
    path('editar-categoria/<int:pk>/', views.editar_categoria, name='editar_categoria'),
    #tarefas
    path('adicionar-tarefa/', views.adicionar_tarefa, name='adicionar_tarefa'),
    path('listar-tarefas/', views.listar_tarefas, name='listar_tarefas'),
    path('listar-tarefas-concluidas/', views.listar_concluidas, name='listar_concluidas'),
    path('apagar-tarefa/<int:pk>', views.apagar_tarefa, name='apagar_tarefa'),
    path('editar-tarefa/<int:pk>', views.editar_tarefa, name='editar_tarefa'),
    # path('', views.pagina_inicial, name='pagina_inicial'),
]

todo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tarefas/', include('tarefas.urls', namespace='tarefas')),
    path('', include('paginas.urls', namespace='pagina_inicial')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <!-- Bootstrap CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

        <title>{% block titulo %} Sistema de ToDO | Senac {% endblock titulo %}</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SENAC - ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'pagina_inicial:pagina_inicial' %}">Página Inicial</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Tarefas </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'tarefas:listar_categorias' %}">Categorias</a>
                                <a class="dropdown-item" href="{% url 'tarefas:listar_tarefas' %}">Tarefas</a>
                                <hr class="dropdown-divider" />
                                <a class="dropdown-item" href="{% url 'tarefas:listar_concluidas' %}">Concluídas</a>
                            </div>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'paginas:fazer_logout' %}">Sair</a>
                        </li>
                    </ul>
                    <div class="d-flex navbar-nav me-auto mb-auto">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="d-flex p-1 alert {% if message.tags == 'success' %}alert-success{% else %}alert-warning{% endif %}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Digite..." aria-label="Search" />
                        <button class="btn btn-outline-success" type="submit">Buscar</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col">

                    {% block corpo %}

                    {% endblock corpo %}

                </div>
            </div>
        </div>

        <script src="{% static '/js/jquery.min.js' %}"></script>
        <script src="{% static '/js/bootstrap.min.js' %}"></script>

    </body>
</html>